### ISSUE TITLE
Operator-first / Applicative

### ISSUE THREAD

**Issue by pbrisbin** [freckle/guides#11]
There are a few styles for `Applicative` expressions

My personal preference:

```hs
parseJSON = withObject "Foo" $ \o -> Foo
  <$> o .: "this"
  <*> o .: "that"
```

Following a broader (but not documented) "operator-last" guide:

```hs
parseJSON = withObject "Foo" $ \o -> Foo <$>
  o .: "this" <*>
  o .: "that"
```

And each of these comes in a "newlined" flavor:

```hs
parseJSON = withObject "Foo" $ \o ->
  Foo
  <$> o .: "this"
  <*> o .: "that"

parseJSON = withObject "Foo" $ \o ->
  Foo <$>
  o .: "this" <*>
  o .: "that"
```

We of course have a mix across our code-bases now; I'd like to standardize that one way or another.

---

I'm not particularly against operator-last as a general guide, however for expressions such as `Applicative`, I strongly prefer operator-first. And I believe much of the team agrees.

There are other expressions in the same category, which I would call "structural" expressions. For example, a lens chain like:

```hs
foo
  <&> bar .~ baz
  <.> bat .~ quiix
```

I call these structural because they look like records or lists. And I think a lot of the team (even if operator-last in general) likes operator-first here because it mirrors the comma-first style of records and lists.

This is in contrast to "functional" expressions, which is where I think folks generally prefer operator-last style:

```hs
foo . bar . baz $
  bat quix

-- vs
foo . bar . baz
  $ bat quix
```

---

So, I would like to raise some questions to the team:

1. Would folks be opposed to prefer-operator-first as our overall guide?
1. If so, would folks be opposed to prefer-operator-first for structural expressions?
1. If so, would folks be opposed to prefer-operator-first for `Applicative` expressions?
1. If so, would folks be opposed to making prefer-operator-**last** explicit in these guides?
1. If so, that means we're OK letting folks do whatever they personally want, are you sure?
1. If we're making a new guide, are we enforcing the newlined constructor or not?

**Comment by jdreaver** [comment]
You make a good distinction between structural and functional style. In ops we obviously have tons of structure and operator-first is necessary for it to not look awful. I wonder if we should come up with more examples to get a feel for how each alternative looks.

I used to be an operator-last kinda guy, but I am starting to like operator-first more.

**Comment by 5outh** [comment]
I typically think that operator-first looks clearer for multi-line expressions. We often have chains of long named things and I think that this:

```hs
fooBlahBlahHahaBlahBlahHaLongName
  . barBlahBlahHahaBlahLongName
  . bazBlahBlahHahaBlahHaLongName
  $ bat quix
```

is a bit clearer than this:


```hs
fooBlahBlahHahaBlahBlahHaLongName .
  barBlahBlahHahaBlahLongName .
  bazBlahBlahHahaBlahHaLongName $
  bat quix
```

Probably worth noting that if you consider `,` an operator, we do "operator-first lists" already:

```hs
[ jinkies
, scooby
, doo
]
```

and the reasoning for this is because the operators now align nicely without any context. I think that's the main reason I prefer operator-first in general.

I don't have a particularly strong opinion on this, but do have a slight preference for operator-first.

EDIT: My preference is the same as yours for the `parseJSON` block.

**Comment by pbrisbin** [comment]
For the record, I too prefer operator-first in general.

**Comment by eborden** [comment]
In my dream world where we move to `brittany` for all Haskell formatting, then we'd be operator first for everything. I support this transition step :grinning:

**Comment by eborden** [comment]
I usually like `newline` constructor as

```
Foo
  <$> o .: "this"
  <*> o .: "that"
```

However, `brittany` does not use `newline`ed and I'm getting use to it.

**Comment by eborden** [comment]
Any feedback on this from @cdparks, @cbeav or @AKurilin?

**Comment by cdparks** [comment]
I generally prefer operator-first, but I'm fine with whatever here.

**Comment by eborden** [comment]
Seems like we've reached near consensus on operator first. :tada:

**Comment by pbrisbin** [comment]
Awesome. I'll move this to PR. One last question:

```hs
        Nothing -> left
            $  Text.pack "could not find parser for node \""
            <> name
            <> Text.pack "\" of type \""
            <> typ
            <> Text.pack "\" at "
            <> file
            <> Text.pack (": " ++ show n ++ ".")
```

The space there between `$  Text.pack`, we good with that?

I like it:

- It looks really nice
- It's not _particuarly_ context-aware alignment
- It passe my rule of "renaming things doesn't require adjusting adjacent lines"

**Comment by tfausak** [comment]
(I'm only commenting on these things because they're public and I have lots of opinions.) A strong :-1: from me for lining things up like that. There are lots of different widths for common operators: `$`, `<>`, `>>=`, `-<.>`, and so on. Attempting to line them up is just going to cause messy diffs for little benefit.

**Comment by eborden** [comment]
@pbrisbin It is context aware alignment, which makes it a :-1: from me.

```
        Nothing -> left
            $  Text.pack "could not find parser for node \""
            <> name
```
vs
```
        Nothing -> left
            . fooo "baz"
            $ bar
```

**Comment by pbrisbin** [comment]
Duly noted -- I'm fine to make the rule without that shift.

However,

> There are lots of different widths for common operators: $, <>, >>=, -<.>, and so on. Attempting to line them up is just going to cause messy diffs for little benefit

This feels like a strawman. I'm having trouble coming up with any type-safe example where you could _only_ replace (e.g.) `(<>)` with `(=<<)` or `($)` in an expression.

I'm not disagreeing that it's "little" benefit, but I do feel it's equally "little" likelihood of messy diffs, in this very specific case.

**Comment by eborden** [comment]
```
baz :: [a]

foo
  . bar
  <$> baz
```
becomes
```
baz :: [Maybe a]

foo
  . bar
  <$$> baz
```

**Comment by pbrisbin** [comment]
Touché :)

**Comment by jdreaver** [comment]
Yeah I'm opposed to any context-sensitive alignment too.
