### ISSUE TITLE
Blank line between extension and module

### ISSUE THREAD

**Issue by pbrisbin** [freckle/guides#12]
(A)

```hs
{-# LANGUAGE OverloadedStrings #-}

module Foo
  ( foo
  ) where

```

(B)

```hs
{-# LANGUAGE OverloadedStrings #-}
module Foo
  ( foo
  ) where

```

(A')

```hs
{-# LANGUAGE OverloadedStrings #-}

-- |
--
-- Foo does the foo-ing
--
module Foo
  ( foo
  ) where

```

(B')

```hs
{-# LANGUAGE OverloadedStrings #-}
-- |
--
-- Foo does the foo-ing
--
module Foo
  ( foo
  ) where

```

**Comment by pbrisbin** [comment]
I prefer B/B' - no blank line. Consider voting with :+1: / :-1: on this comment.

**Comment by cdparks** [comment]
Prefer blank line, but not a strongly-held opinion.

**Comment by eborden** [comment]
A/A for me.

**Comment by jdreaver** [comment]
Yeah I'm all about the blank line. It's like a new paragraph in my mind and deserves some space.

**Comment by pbrisbin** [comment]
That's too bad, it looks particularly ugly to me when the Haddocks are present (B). I'll go ahead and open the PR to canonicalize this, since I seem clearly out-voted.

**Comment by tfausak** [comment]
As an outsider, I also prefer A/A' 🙂 All the pragmas affect how the file gets processed, so it feels like there should be some space between that metadata and the actual data/code in the file.
