### ISSUE TITLE
default-extensions rule

### ISSUE THREAD

**Issue by pbrisbin** [freckle/guides#13]
The current rule is we do not use `default-extensions`; extensions should always be specified in the module that uses them.

We should revisit:

1. I believe people didn't realize this was coming in when it was introduced
1. Some cases such as `NoImplicitPrelude` really should be in defaults

This issue serves as additional awareness, to resolve (1) even if we change nothing.

To address (2), I would propose we change the guide to specify an explicit list of extensions that are allowed in `default-extensions` and enforce that all others are enabled by pragma. I would begin concervatively with `[NoImplicitPrelude]` being the safe-list, but welcome suggestions from others.

**Comment by cdparks** [comment]
> The current rule is we do not use default-extensions; extensions should always be specified in the module that uses them.

Yeah, I don't think I knew this was the rule. Nearly every one of our packages has `default-extensions` (mostly syntactic)

**Comment by 5outh** [comment]
The haskell survey might be a good place to start with regards to this question: http://taylor.fausak.me/2017/11/15/2017-state-of-haskell-survey-results/#question-21

Some thoughts:

- `TypeApplications` is used in every `Graphula` test we have, so it might make sense to have that on by default for our test suites.
- No extensions restricted or forbidden by `SafeHaskell` should be enabled by default: https://ghc.haskell.org/trac/ghc/wiki/SafeHaskell#SafeLanguage

Extensions I wouldn't mind being on by default:

- `OverloadedStrings`: We use `Text` as a String value constantly.
- `BangPatterns`: Record fields are typically strict
- `LambdaCase`: I use this style all the time and it has a very low overhead
- `ScopedTypeVariables`: Extremely convenient while developing and validating assumptions about the types of things
- `TypeApplications`: Especially as our types get a bit more generic/ambiguous, it might make sense to just have the ability to apply types all the time.

**Comment by eborden** [comment]
Yeah, there is a subset of extensions that I consider Haskell 2020:
- `OverloadedStrings`
- `BangPatterns`
- `LambdaCase`
- `ScopedTypeVariables`
- `TypeApplications`

Those extensions are pretty standard and don't have strange interplay with other extensions.

Eventually I'd love to turn on the deriving family of extensions, but right now we don't have `DerivingStrategies`, so they can have strange interplay.

**Comment by pbrisbin** [comment]
I'm going to call Ben and Evan's list "Haskell2020" for the duration of this comment. At the end, I'll make the proposal that involves the concrete extensions in said list, but in the middle I want to talk about the idea of a Haskell2020 list itself.

---

The justification in the existing rule is this:

>  This ensures a) the source code works un-changed with other Haskell tooling
>  (e.g. `ghci`, `doctest`, etc) without further configuration and b) active
>  extensions are visible in the modules they impact.

I'd like to extend this justification in two ways:

1. I should've put HLint in the list for (a); it [is impacted by this](https://github.com/frontrowed/megarepo/blob/master/.hlint.yaml#L23) and is probably a more real-world example: we're maintaining [multiple lists](https://github.com/frontrowed/megarepo/blob/master/haskell/backend/fancy-api/.ghci) of `default-extensions` and are accepting that they're often mismatched between the tooling and individual projects.
1. Another benefit of in-file, let's call it (c), is HLint can tell us if an extension is unnecessary in that file. I despise having things turned on that aren't necessary.

My suggestion of `[NoImplicitPrelude]` was not an attempt to define a Haskell2020 of only that extension. It was an attempt to preserve (a), (b), and (c), while admitting that this particular extension really should be on by default if it's used at all.

The approach of deciding on our Haskell2020 as the blessed list preserves (b) and (c) IMO, but gives up on (a). If you're all comfortable with that, then I won't stand in the way.

It looked like most folks have already mentally decided on a Haskell2020 approach and jumped right to discussing what it should be, so I just wanted to clarify my own original stance.

Sorry if that was all obvious already; I'm an over-explainer.

---

The current proposal, shared by two parties, is:

- BangPatterns
- ScopedTypeVariables
- TypeApplications
- OverloadedStrings
- LambdaCase

I'm personally :+1: on this list. I would prefer the guide _require_ these are set in `default-extensions` to make our programming environment consistent across projects.

I would add `NoImplicitPrelude` as _legal_ but not _required_ in `default-extensions`, for the reasons I mentioned above.

I would prefer the guide _forbid_ any other extensions in `default-extensions`, for the original justifications of (b) and (c).

**Comment by eborden** [comment]
@pbrisbin I'm not completely opposed to preserving (a). I find that it maintains the principle of least astonishment when all extensions are listed in a module. I think the primary objection comes down to how much boilerplate we want to write. I could go either way. I'm totally fine with boilerplate and I like visibility.

**Comment by cdparks** [comment]
I would also add:
* `GADTs` since it enables a syntactic extension _and_ usage of `~`
* `MultiParamTypeClasses` and `Flexible(Contexts|Instances)` for `persistent` and `mtl`
* `TypeFamilies`, `DataKinds`, and `KindSignatures` (used for `HasField` and a bunch of other ad-hoc type families)

**Comment by 5outh** [comment]
@cdparks How does enabling those extensions for files that don't use them affect the speed of compilation? Most of these seem like  relatively "heavy" extensions, but I'm not sure of the exact perf implications

**Comment by cdparks** [comment]
Almost all of these have a syntactic component that should prevent ghc from running irrelevant code unless you're actively using them. `TypeFamilies` is really the only one where `ghc` might have to disambiguate semantically between things that are type families and things that aren't.

**Comment by pbrisbin** [comment]
:wave: I'd like to revive this Issue and see if we can reach a consensus. The current guide is not being followed so I'd like to either update and follow it, or remove it.

Over in teacher-daily-mailer, I committed (somewhat sneakily) a reduced `default-extensions`. I think we could use this as an in-the-wild data point. The list I committed there is:

```yaml
default-extensions:
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RecordWildCards
  - TemplateHaskell
  - TypeFamilies
```

I came about this in a bit of an ad-hoc way:

- `NoImplicitPrelude`: you really need this to be defaulted if you're going to use it
- `NoMonomorphismRestriction`: I was bit by something recently when not having this on and it was a *wildly* confusing error message, I think we agree team-wide this should be default
- `OverloadedStrings`/`RecordWildCards`: these are so pervasive and useful in our own code-bases we'd have them enabled in virtually every module if they weren't defaulted
- `TemplateHaskell`/`TypeFamilies`: this *felt* pervasive in teacher-daily-mailer specifically, but I could be convinced otherwise.

Given this experience, and re-reading over this thread, I would like to propose the following list as our prescribed `default-extensions`, leaving everything else to `LANGUAGE`:

```yaml
default-extensions:
  # Uncontested
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings

  # From my own experience in teacher-daily-mailer
  - RecordWildCards

  # From Evan and Ben's input, which Chris and I were in favor of
  - BangPatterns
  - ScopedTypeVariables
  - TypeApplications
  - LambdaCase
```

At the moment, I've left off @cdparks' additions because they just feel too heavy-weight to me. I enabled them via `LANGUAGE` as needed in teacher-daily-mailer and FRTool (still an open PR) and it was not cumbersome (IMO), and I do find it valuable to know when I'm in a module that is using such extensions. The ergonomics are likely to be different in a more complex app (e.g. something Yesod-backed), but I don't know that we should optimize our guides for that.

I'm curious what others think about my proposal as-is and if I added some or all of Chris's suggestions.

**Comment by cdparks** [comment]
> TemplateHaskell/TypeFamilies: this felt pervasive in teacher-daily-mailer specifically, but I could be convinced otherwise.

`TemplateHaskell` is pervasive in `FrontRow/Entities/*`, and `TypeFamilies` is used by `graphula` and a ton of `persistent` stuff. I thought it only had to be enabled when you want to declare type families, but you also need it to define type instances, e.g.:
```plaintext
> data Stuff = Stuff { stuff :: Int }
> instance HasDependencies Stuff where
|   type Dependencies Stuff = Only Int
| 
<interactive>:4:3: error:
    • Illegal family instance for ‘Dependencies’
        (Use TypeFamilies to allow indexed type families)
    • In the type instance declaration for ‘Dependencies’
      In the instance declaration for ‘HasDependencies Stuff’
```

**Comment by cdparks** [comment]
`-XDeriveGeneric` is also used pervasively throughout the entire codebase. `-XStandaloneDeriving` is used to a lesser extent, mostly for defining `Hashable` for `Key`s of `persistent` entities.

**Comment by pbrisbin** [comment]
I'm fine adding `TemplateHaskell`, `TypeFamilies` and `DeriveGeneric` to our always-defaults list. I think `StandaloneDeriving` can still be an "as-needed" case, since it very often goes hand in hand with orphans it should be getting less pervasive for us going forward.

**Comment by pbrisbin** [comment]
Updated proposal then:

```yaml
default-extensions:
  # Uncontested
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings

  # From my own experience in teacher-daily-mailer
  - RecordWildCards

  # From Evan and Ben's input, which Chris and I were in favor of
  - BangPatterns
  - ScopedTypeVariables
  - TypeApplications
  - LambdaCase

  # At Chris's suggesting
  - DeriveGeneric
  - TemplateHaskell
  - TypeFamilies
```

**Comment by 5outh** [comment]
This looks great! The one contention I have is that I don't think `TemplateHaskell` should be on by default. While a lot of things can and are generated using `TemplateHaskell`, they're largely localized and we typically try to avoid using it where possible.

One exception is test suites, where we commonly use e.g. `aesonQQ`. But I think avoiding TH by default is probably a good idea to prevent us from littering code with too much generated stuff. WDYT?

**Comment by eborden** [comment]
I'd like `RankNTypes` in there. As well I don't think `TemplateHaskell` should be on by default.

**Comment by cdparks** [comment]
I'm fine losing `TemplateHaskell`, I think we actually have more `QuasiQuotes` than that:
```haskell
[persistLowerCase| ... |] -- only FrontRow/Entities/*
[st| ... |] -- rawSql or mailers
[hamlet| ... |] -- mailers
[aesonQQ| ... |] -- tests
```

**Comment by eborden** [comment]
I'm actually kind of curious what the implications of `TemplateHaskell` and `QuasiQuotes` are on the compiler. I know they require a two stage compilation, but does GHC completely avoid those stages with them turned off?

**Comment by pbrisbin** [comment]
Do the thumbs-ups there mean you'all want `QuasiQuotes` in?

New proposal:

```yaml
default-extensions:
  # Uncontested
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings

  # From my own experience in teacher-daily-mailer
  - RecordWildCards

  # From Evan and Ben's input, which Chris and I were in favor of
  - BangPatterns
  - ScopedTypeVariables
  - TypeApplications
  - LambdaCase

  # At Chris's suggesting
  - DeriveGeneric
  - TypeFamilies

  # Evan's request
  - RankNTypes
```

**Comment by eborden** [comment]
Are we planning to update all the defaults and deal with the resulting fallout? I'm on the fence about `QuasiQuotes`. I could go either way.

**Comment by pbrisbin** [comment]
> Are we planning to update all the defaults and deal with the resulting fallout?

I wasn't planning to do this in a big-bang way, but I'm happy to do it in components as I touch them.

**Comment by 5outh** [comment]
I'm anti default quasi-quotes, but I think it's acceptable to turn them on by default in tests, if we're willing to make that caveat known.

**Comment by pbrisbin** [comment]
OK, proposed new guide:

>  You SHOULD use the following `default-extensions`:
>
> - NoImplicitPrelude
> - NoMonomorphismRestriction
> - OverloadedStrings
> - RecordWildCards
> - BangPatterns
> - ScopedTypeVariables
> - TypeApplications
> - LambdaCase
> - DeriveGeneric
> - TypeFamilies
> - RankNTypes
>
> This defines a consistent, and minimally-extended Haskell environment. Other extensions should be defined via `LANGUAGE` pragmas in the modules where they're needed.
>
> Accepted violations of the guide include:
>
> - Adding `QuasiQuotes` in Entity-definition-heavy packages
> - Adding `QuasiQuotes` in test targets making frequent use of `aesonQQ`

**Comment by pbrisbin** [comment]
On second thought, having caveats in the guide feels like an anti-pattern. I think I'd prefer we go with that list, call the rule a `SHOULD`, but not have the "Accepted violations" bit. We can all just understand that if someone wants to add something like `QuasiQuotes` for the reasons mentioned, and they get through Code Review, that's fine.

WDWT? Should I proceed with a PR under that plan?

**Comment by eborden** [comment]
Isn't the intent behind having a consistent list to prevent breakage in tooling like `hlint`, etc. From this perspective anything outside the list would be a violation and cause issues.

**Comment by pbrisbin** [comment]
That is true, but how many and how large of issues is a spectrum, so  (it seemed) some on the team felt it could be worth it to violate this rule in some scenarios, hence `SHOULD`. Maybe if we encounter such issues concretely down the line, those opinions could change.

I'm personally on board with making this a `MUST` rule for exactly that reason, but I am willing to yield in order to build consensus.

**Comment by pbrisbin** [comment]
I opened the PR with the stricter take. I added Evan and Ben only as reviewers since (I think) they're the only participants who might be disagreeing in this regard at this point.
