### ISSUE TITLE
Brittany

### ISSUE THREAD

**Issue by pbrisbin** [freckle/guides#22]
We've toyed with the idea of [Brittany](https://github.com/lspitzner/brittany#readme) and discussed it many times. Team buy-in seems a bit mixed: some are interested but skeptical, others are :100: on board, and still others are merely tolerant. But I don't think anyone is against it.

To this point, we've held off on pushing Brittany because there are some things it doesn't handle and other things it handles poorly. I think it's time we revisit that idea.

This Issue is an attempt to reach consensus on:

1. [x] Should we start auto-formatting Haskell modules with Brittany?
1. [x] If so, should we do big-bang or some form of incremental?
1. [x] If big-bang, when/how do we execute on that?

In addition to the discussion which I'm sure will ensue, I've also left some emoji in the body, which you can react to this Issue with if you hold those feelings.

## Why Now?

Brittany, as of v0.11, has comment pragmas for ignoring declarations. There are some caveats (e.g. you can only ignore a top-level expression), but this means we can leave some expressions that Brittany makes objectively worse un-formatted. This is really the key reason we could make the jump now, if we wanted to.

## 1- Should we?

Please :+1: / :-1: this Issue.

### Big-bang

Brittany up all the Haskell in one monster commit. Maybe do a package at time?

**PROS**: sets an epoch in git history, avoids additional per-module discussions, Frontend had success doing this approach with prettier.

**CONS**: we won't get to do pragma-disabling if there are things we don't like, this means there is a higher burden of up-front research for how brittany will handle various code-constructs.

:tada: if in favor of this option.

### Incremental

- New modules get Brittanied
- Existing modules get Brittanied when touched

**PROS**: we can see how Brittany changes things as it happens and make configuration tweaks or employ pragma-disabling.

**CONS**: we will have to evaluate how Brittany changes things as it happens, and likely have a lot of additional discussion on the specific points and if/when to pragma-disable. We wouldn't be able to turn on editor "auto-format-on-save" and/or maybe we'd have to be a bit more careful about separating re-formatting commits in PRs.

:smile:  if in favor of this option.

**NOTE**: nothing is preventing us from doing incremental for some short acclimation period then big-bang after.

## 3- When / How?

https://github.com/frontrowed/guides/issues/22#issuecomment-400800997

## Appendix: Line Length

I'm going to strongly advocate for a Brittany setting of 80 columns, not 120.

I understand why we have our current guide of 120. I'm on board with that reasoning. We have long identifiers, we should allow longer lines because of that. I get it.

The difference is that with the current guide, while you're _allowed_ 120 columns, you aren't _required_ to use 120 columns. A human can still wrap lines more tightly when it makes sense and you don't end up with a module that makes no use of vertical space at all.

Brittany can't do that. If you configure Brittany with 120 columns, it will use that full width all the time. This *drastically* increases the number of lines that will actually reach closer to 120 and makes terrible use of vertical space. This is a case where the auto-formatter would be actively hurting code readability.

I'm only mentioning this now to avoid later surprise. If this Issue is gaining traction, but there is uncertainty about going with a setting of 80, I will attempt to make a stronger case through concrete examples where I think Brittany-120 would be harmful.

Toss me a :heart: if you're in favor of 80.

**Comment by eborden** [comment]
A simple example of 120 vs 80:
```
replaceIfUpdated :: (MonadIO m) => Entity Teacher -> Teacher -> SqlWriteT m (SyncResult (Entity Teacher))
replaceIfUpdated oldTeacherEntity@(Entity teacherId oldTeacher) teacher = if null mergeUpdates
  then return $ Unchanged oldTeacherEntity
  else Updated . Entity teacherId <$> updateGet teacherId mergeUpdates
  where mergeUpdates = getTeacherMergeUpdates oldTeacher teacher
```
```
replaceIfUpdated
  :: (MonadIO m)
  => Entity Teacher
  -> Teacher
  -> SqlWriteT m (SyncResult (Entity Teacher))
replaceIfUpdated oldTeacherEntity@(Entity teacherId oldTeacher) teacher =
  if null mergeUpdates
    then return $ Unchanged oldTeacherEntity
    else Updated . Entity teacherId <$> updateGet teacherId mergeUpdates
  where mergeUpdates = getTeacherMergeUpdates oldTeacher teacher
```

**Comment by 5outh** [comment]
I'm going to carve out some time to (finally) mess with `brittany` today. I find the `prettier` workflow incredibly freeing, so I'm _pretty sure_ I'm in favor of this change. I want to mess around with it a bit before voting, though.

My default code style is 80 characters as well, but I'm particularly curious how it handles some of our nastier `SqlPersistT` blocks, like this one I just plucked:

```hs
fetchElaAnswerDataFromSessions :: MonadIO m => [DistrictElaAssessmentAssignmentSessionId] -> SqlReadT m [RawElaSessionAnswerRow]
fetchElaAnswerDataFromSessions sessionIds = (unValue5 <$$>) $
  select . from $ \(assessments `InnerJoin` assignments `InnerJoin` sessions `InnerJoin` answers `InnerJoin` assignedStudents) -> do
    on $ assignedStudents ^. DistrictAssessmentAssignedStudentStudentId ==. sessions ^. DistrictElaAssessmentAssignmentSessionStudentId
      &&. assignedStudents ^. DistrictAssessmentAssignedStudentAssessmentId ==. assessments ^. DistrictAssessmentId
    on $ answers ^. DistrictElaAssessmentAssignmentAnswerAssessmentSessionId ==. sessions ^. DistrictElaAssessmentAssignmentSessionId
    on $ sessions ^. DistrictElaAssessmentAssignmentSessionAssignmentId ==. assignments ^. DistrictElaAssessmentAssignmentId
    on $ assignments ^. DistrictElaAssessmentAssignmentDistrictAssessmentId ==. assessments ^. DistrictAssessmentId
    where_ $ sessions ^. DistrictElaAssessmentAssignmentSessionId `in_` valList sessionIds
    return
      ( assessments ^. DistrictAssessmentAssessmentContentId
      , sessions ^. DistrictElaAssessmentAssignmentSessionStudentId
      , sessions ^. DistrictElaAssessmentAssignmentSessionCompletedAt
      , answers ^. DistrictElaAssessmentAssignmentAnswerQuestionUuid
      , answers ^. DistrictElaAssessmentAssignmentAnswerCorrectness
      )
```

Will get back with some emoji-votes later!

**Comment by pbrisbin** [comment]
FWIW, I've been `brittany-disable`-ing those nastier Esqueleto functions. It gets it wrong in all kinds of ways, regardless of line-length.

**Comment by jdreaver** [comment]
@pbrisbin and I were discussing using that comment pragma to ignore more DSL-like functions. In particular, I think our `esqueleto` code and `stratosphere` code are good candidates. In these cases, it's nice to have the layout the programmer intended:
* For the `esqueleto` case, we want it to look like SQL, with different parts of the query on their own line
* For `stratosphere`, we want it to look like a CloudFormation template, with config values all on their own line, and with proper nesting when a config value is itself another record type.

I'm not sure where we will all land on that idea, just throwing it out there for discussion.

**Comment by pbrisbin** [comment]
optparse-applicative is another example I'd toss in as disable-able. I think it's valuable to have them resemble the `--help` they represent.

**Comment by tfausak** [comment]
For what it's worth, we (@EdutainmentLIVE) recently did a big-bang switch from `hindent` to Brittany. It went well and I'd recommend it! A few caveats though:

- In general I think our code is "simpler" than yours. We don't use many language extensions, for example.
  - As a result, I don't think we use pragmas to disable or configure Brittany anywhere. 
- https://github.com/lspitzner/brittany/issues/17: Brittany doesn't format instance methods. You can manually solve this by formatting them at the top level and then moving them into the instance, but it's annoying.
- https://github.com/lspitzner/brittany/issues/47: Brittany doesn't format data declarations. `hindent` does pretty well with these, so running everything through `hindent` first and then `brittany` spits out some decent output even though it's a ridiculous workflow. 

Overall we like how Brittany formats things much better than `hindent`. We have some minor quibbles, but the consistency has been nice. My main complaint is that Brittany seems to be more or less supported by one person, so development is slow. None of us have taken the time to implement changes, perhaps because the codebase is somewhat intimidating.

**Comment by eborden** [comment]
@tfausak I'd recommend attempting a PR for `brittany`. The codebase looks intimidating at first, but it has a few strong and simple idioms that become clear once you dig in.

**Comment by tfausak** [comment]
Good to know! I've had "contribute to Brittany" on my to-do list for about a month now. Hopefully I'll be able to find some time around the upcoming July 4th holiday 🇺🇸 🇺🇸 🇺🇸

**Comment by 5outh** [comment]
Okay, I messed around with this and have voted. I think @jdreaver's noted exceptional cases certainly have a flavor to them, which is good enough for me to constitute a special rule.

I'm strongly in-favor of a big bang release for consistency's sake. My one concern is that we'll need to annotate each of our DSL functions before making the big-bang change, which could eat up a good amount of time if we're thorough about it.

That said, I tried out brittany and immediately felt great about it. My code style preferences are largely "I don't care, as long as it's consistent". Formatting code is a mental burden, and if we can remove it entirely, I'm highly in favor.

**Comment by pbrisbin** [comment]
> My one concern is that we'll need to annotate each of our DSL functions

FWIW, we could also go the other way:

1. Big-bang without annotations
1. Let people manually re/un-format and annotate things as they see them, if they feel so strongly

**Comment by jdreaver** [comment]
I wonder, are there any more modifications to `brittany` we want to make before doing a big bang conversion of our code to it? I know @eborden mentioned opening some PRs a while back. Is there anything `britanny` still does that we don't like, now that we fixed a lot of context-sensitive indentation issues?

**Comment by pbrisbin** [comment]
> I wonder, are there any more modifications to brittany we want to make before doing a big bang conversion of our code to it?

@jdreaver FWIW that's exactly where this initiative stalled last time. I'd be concerned that that line of thinking will leave us in the same place. The ability to pragma-disable out of hypothetical blockers was really the only new information to spur this thread.

**Comment by pbrisbin** [comment]
(I'm going to remove Assignees after they've voted, so we know who's outstanding. Also, feel free to remove yourself if you prefer to abstain.)

**Comment by eborden** [comment]
Another option for the record formatting issue is utilizing `stylish-haskell`, which is already part of our tool-chain for import formatting.

**Comment by eborden** [comment]
@jdreaver there were some bugs in `brittany` that were blocking a big bang last time. I believe most have been resolved. The TH issues might still be floating around.
https://github.com/lspitzner/brittany/issues/90

**Comment by pbrisbin** [comment]
The TH issue is annoying. I will often have to exclude TH-containing files in Restyled to prevent errors. Though it seems to only choke on quasi-quotes, which can sometimes force me to [push that content out to files](https://github.com/frontrowed/megarepo/blob/master/ops/haskell/library/FrontRow/Ops/Templates/Job.hs#L155), which I'm generally happier with anyway.

**Comment by pbrisbin** [comment]
@stackptr @rogers89 would you like to vote on this issue, or would you rather abstain?

**Comment by cdparks** [comment]
I think the output of whatever we use on frontend (`prettify`?) looks like garbage most of the time, but i don't care anymore because it's the machine's fault! I have similar reservations with `brittany`, but I'm sure I'll get used to it, and as long as we can disable occasionally (specifically `esqueleto`), I'm down.

**Comment by jdreaver** [comment]
Yeah my only objection is I don't like the style a lot of the time, but I could probably get used to it too.

**Comment by eborden** [comment]
_In before someone mentions structured editing_

We have to weigh the options:
1. Don't like the style
2. Don't like thinking about style

You'll basically always have *1*, unless you are the individual writing the style specification. You can only get to *2* by writing your own tool or accepting *1* as a fact of life. So if *2* is the most important goal then *1* must suffer.

**Comment by pbrisbin** [comment]
Folks. I think we have consensus!

- Yes Brittany :+1:
- Yes big-bang :tada: 
- Yes 80 columns :heart: (omg thank you)

Now we get to hash out how.

Does anyone want to propose something? If not I will, but I really don't care how it happens, I'm just stoked that it will.

**Comment by pbrisbin** [comment]
OK, so don't all jump in at once to propose a plan :joy: 

How about this:

_From the point at which this Issue Closes_

1. Entirely new modules _should_ get Brittanied and receive no style comments in PR (except maybe "is this Brittanied?", "yes.")
1. ~~Touched modules _may_ get Brittanied if it doesn't hinder Code Review (e.g. if you use a separate commit or the changes are easily distinguished)~~
1. @pbrisbin will announce a willingness to help with editor configurations in Slack
1. @pbrisbin will make a list of our Haskell packages in a Google Sheet
1. Backend engineers should claim packages that they will Brittany in a PR
1. Owners of such PRs should coordinate with the team in Slack to avoid conflicts

   This bit is kept purposely un-specified, it worked fine for Frontend. Packages that are infrequently edited can probably just go without any coordination -- choose wisely ;)

_After all such PRs are merged_

1. All modules _must_ be Brittanied (engineers should flip on `on_save` settings)
1. We will _consider_ some kind of enforcement (Restyled?), but only rely on code review to start

At some appropriate point, someone will update our style guide to just say "use Brittany" and remove any guides that are redundant with that.

Please toss me a :+1: on this comment, or propose something different.

@eborden @cdparks @5outh @jdreaver

**Comment by jdreaver** [comment]
Is this for all Haskell code, or just everything under `haskell/`? We've discussed a lot of the problems with britanny in DSL-like code, especially with `stratosphere` in `ops`. I'd like to punt on using brittany in `ops` at least until we have a good system for ignoring `stratosphere` code.

**Comment by pbrisbin** [comment]
@jdreaver I assumed you would sign up for the `ops` package and we could find some way to move forward (maybe by `brittany-disable`ing a lot, maybe by not including `ops` in this initiative).

**Comment by eborden** [comment]
Item 2 seems to be in conflict with the consensus around a big bang.

**Comment by pbrisbin** [comment]
@eborden stricken.

**Comment by pbrisbin** [comment]
We have reached consensus :tada:
