### ISSUE TITLE
Handlers Naming Conventions

### ISSUE THREAD

**Issue by pbrisbin** [freckle/guides#23]
I would like to propose a new naming convention for Yesod Handler modules.

## Context

We do not have a well-established convention. We have a _slight_ majority for:

```
FrontRow.Api.{Namespace}.Handler.{Resource}
```

Which is also what I see most often suggested for new modules.

I think there are intentional nuances to this convention that allow `.{Resource}` to be omitted/reversed (`ActivityFeed.Handler`) and/or `{Namespace}` to be split across `.Handler.` (`Ela.AdaptiveSkill.Handler.Courses.Sessions`), but these are not uniformly followed because I think such nuances (if they exist) are too complicated. We also don't consistently pluralize or singularize `Namespace` or `Resource`, with a slight preference for singular.

(For those interested, and who have not yet seen it, I have a private gist that catalogs our current modules. Please ask in Slack.)

A different but related inconsistency is how we name routes and route-constructors in general. I'm proposing something for that as part of this. The route-constructor should related the module back to the route, so standardizing the two together is important.

## Motivation

All of this ends up making it difficult to (a) know where to put a new Handler and (b) locate an existing Handler.

An additional, but minor, issue is that having the "category" (`Handler`) in the middle of the path does not play well with any tooling that likes to operate in the style of `Handler/*` or `*/Handler.hs`. Rarely do they support `*/Handler/*`, especially when what comes before and after is itself inconsistent (split-`Namespace`) or often omitted (dropping `Resource`).

## Proposal

**route**

```
{namespace}/{resource} {Namespace}{Resource} GET
```

**module**

```
FrontRow.Api.Handlers.{Namespace}.{Resource}
```

**Optionality**:

Please indicate which you prefer:

- A: `Namespace` and `Resource` are always singular (`Handlers.Teacher.Student`)
- B: `Namespace` and `Resource` are always plural (`Handlers.Teachers.Students`)

The rest of this proposal assumes (A), but I have no personal preference.

**Notes**:

- Each `/` in the `{namespace}` route is a `.` in the `Namespace` module
- If you end up with a `Namespace` like `TeachersTeacher` because of a route like `/teachers/:id`, which would lead to a module like `Teacher.Teacher`, omit the `Teachers` prefix -- see *Examples*, it's not as complicated as it sounds

## Examples

```
teachers TeachersP:
  / TeachersR GET
  /#TeacherId TeacherP:
    / TeacherR GET
    /schools TeacherSchoolsR GET
    /students TeacherStudentsR GET

FrontRow.Api.Handlers.Teacher
  getTeachersR
  getTeacherR

FrontRow.Api.Handlers.Teacher.School
  getTeacherSchoolsR

FrontRow.Api.Handlers.Teacher.Student
  getTeacherStudentsR
```

## Optional

We could define `FrontRow.Api.Handlers` which re-exports `Handlers/*`. We could maintain this manually, or write a small executable like `hspec-discover` that does it automatically. Such a project may even already exist.

**Comment by tfausak** [comment]
> We could define `FrontRow.Api.Handlers` which re-exports `Handlers/*`. We could maintain this manually, or write a small executable like `hspec-discover` that does it automatically. Such a project may even already exist.

My [Autoexporter](https://github.com/tfausak/autoexporter/tree/62d3e42be64b853266054d245767befc93604876) package does exactly that. Unfortunately it seems to have fallen out of Stackage nightlies 🤔

**Comment by 5outh** [comment]
Thanks for writing this up formally! This is exactly how I have been thinking about our file structure for Handler modules, with one miniscule divergence:

> Namespace and Resource are always singular

`namespace` and `resource` (lower case) are always plural in the route. Why not go the other direction and use plural `Namespace`s and `Resource`s? I'm curious if there is a reason for this apart from previous conventions.

Whichever way this goes, I'm :+1: on the change!

**Comment by pbrisbin** [comment]
I wouldn't even start up that hill let alone die on it, but here is my thinking, FWIW:

Starting with `Resource`:

- I don't think we want to get so granular as to have `Handlers.Teachers.getTeachersR` and `Handlers.Teacher.getTeacherR`, so
- The "teacher handler" module will contain functions that "handle" one value (`getTeacherR`) or many values (`getTeachersR`)
- It's natural for me to think `getTeachersR` is handling many of a "Teacher" resource, but
- I wouldn't say `getTeacherR` is handling one of the "Teachers" resource(s?)
- Therefore, I just think of it as `Handlers.Teacher`: the handler for the Teacher resource

I decided to apply that back to `Namespace` because I think it'll be frequent that we'll have a module-piece that is both a `Namespace` and itself a `Resource`:

```
FrontRow.Api.Handlers.Teacher
FrontRow.Api.Handlers.Teacher.Student
```

This makes me feel warm and fuzzy. But if we said `Namespace` needs to be plural, while `Resource` needs to be singular, we would end up with `Teachers` and `Teacher` in the module tree, which does not make me feel warm and fuzzy.

**Comment by pbrisbin** [comment]
The more I think about it, the more I'd be totally fine with both plural. I'll add that optionality to the proposal and we can see what the team thinks.

**Comment by 5outh** [comment]
@pbrisbin Thanks for the stream of consciousness :+1: I think what you're saying makes sense. My thinking was that, for example, `getTeacherR` would still live in `FrontRow.Api.Handlers.Teachers`, not a separate (singular) module, FWIW.

**Comment by 5outh** [comment]
Oh, where would `Dal` modules live in this scheme?

**Comment by pbrisbin** [comment]
I'm keeping the scope of this intentionally limited to `Handler` modules. The others would be tackled separately.

**Comment by pbrisbin** [comment]
FTR: we have exactly two cases that use `Handler` and `Dal`, which could be impacted by our decision:

```
FrontRow.Api.Course.Handler.AssignmentCounts.Dal
FrontRow.Api.Course.Handler.ClassGroupingReport.Dal
```

I don't care what we do with these. I think these would be viable options:

- Move them accordingly (`Handlers.Course.AssignmentCounts.Dal`)
- Remove "Handler" from their module paths (`Course.AssignmentCounts.Dal`)
- Leave them where they are

**Comment by 5outh** [comment]
I just want to throw out the observation that most API endpoints have an associated `Dal` coupled along with them currently (In `Helper/Dal`). By moving all Handlers into a dedicated top-level directory, we will run into duplication of the file tree in the meantime.

If we consider the coupling of Dal/Handler modules an anti-pattern, then this proposal will nudge us in the right direction. If not, we run the risk of nesting a bunch of `Dal` modules under the `Handlers` top-level directory, which feels wrong. I'm curious if anyone feels strongly that the coupling is _not_ an anti-pattern we should avoid.

**Comment by pbrisbin** [comment]
> [M]ost API endpoints have an associated Dal coupled along with them currently (In `Helper/Dal`). By moving all Handlers into a dedicated top-level directory, we will run into duplication of the file tree in the meantime.

Can you unpack "duplication of the file tree"? I'm not sure what you mean.

> If not, we run the risk of nesting a bunch of Dal modules under the `Handlers` top-level directory, which feels wrong

I don't think that's right. I think you might be inferring something about this proposal that is not there. The only such examples where this proposal might imply moving a `Dal` module under a `Handlers/` are the two specific cases I mentioned in my last comment.

Taking 3 other hopefully-illustrative examples:

```
FrontRow.Api.ActivityFeed.Handler
FrontRow.Api.ActivityFeed.Helper.Dal

FrontRow.Api.Handler.CourseMemberships
FrontRow.Api.Dal.CourseMemberships

FrontRow.Api.Article.ResumableSessions.Handler
FrontRow.Api.Article.ResumableSessions.Dal
```

This proposal would like to see that become:

```
FrontRow.Api.Handlers.ActivityFeed
FrontRow.Api.ActivityFeed.Helper.Dal

FrontRow.Api.Handlers.CourseMembership
FrontRow.Api.Dal.CourseMemberships

FrontRow.Api.Handlers.Article.ResumableSession
FrontRow.Api.Article.ResumableSessions.Dal
```

So just leaving the `Helper/Dal` modules where they are, to be dealt with through orthogonal proposals (specifically, removing "Helper", and considering if a category such as "Dal" is valuable).

Does that make some aspects of our module tree worse, sure. Does it make it _much worse_? I dunno. Does it make it _so much_ worse that we should attempt to account for it at the same time and risk making so much work that we don't make any progress? Maybe, but that's the risk I was trying to stay away from initially.

If I were to propose other changes to account for this, I would propose:

- Remove `Helper` anywhere it appears. It's useless
- Apply the same pattern we have for `Handler` to `Dal`: `FrontRow.Api.Dal.{Namespace}.{Resource}` (singular)

If it's an easy win to get those proposals "passed" along with this one, I'm down. I was concerned I couldn't build consensus taking such an ambitious stance.

**Comment by 5outh** [comment]
> Can you unpack "duplication of the file tree"? I'm not sure what you mean.

Sure; it looks like we'll end up with a file tree that looks like this:

```hs
- FrontRow
  - Api
    - Handlers
      - Article
        - ResumableSession
      - CourseMemberships
      - ActivityFeed
    - Dal
      - Article
        - ResumableSession
      - CourseMemberships
      - ActivityFeed
```

In which case, `Handlers` and `Dal` mirror each other (duplicating the structure of the directory tree). One alternative world is to segment on resource type instead of function; for example:

```hs
- FrontRow
  - Api
    - Article
      - ResumableSession
        - Handler
        - Dal
    - CourseMemberships
        - Handler
        - Dal
    - ActivityFeed
      - Handler
      - Dal
```

In other words:

```
FrontRow.Api.Handlers.{Namespace}.{Resource}
```

becoming

```
FrontRow.Api.{Namespace}.{Resource}.{Function}
```

(where `Function` is `Handler` or `Dal`, or whatever else is in `Helpers` at the moment)

is an alternative proposal.

I think this statement is totally fair, too:

> Does it make it so much worse that we should attempt to account for it at the same time and risk making so much work that we don't make any progress? Maybe, but that's the risk I was trying to stay away from initially.

At a certain point I'm just bikeshedding, but I did want to clarify.

**Comment by pbrisbin** [comment]
Gotcha. [If we decided to keep `Dal` at all] that "duplicated" file-tree is actually kind of my own preference -- categories as the first level with symmetrical paths below. But happy to hear others' takes.

**Comment by jdreaver** [comment]
Yeah I like @5outh's proposal. Keeping similar modules nearer in the hierarchy (i.e. the Handler and Dal for the same endpoint) seems much more logical than mirroring hierarchies. In fact, isn't that similar to what we've tried to accomplish in the past?

**Comment by pbrisbin** [comment]
I think that `Handlers.*` is objectively better than `*.Handler` because it makes our module tree a more useful taxonomy to explore.

I think Ben's approach considers these labels (`Handlers`, `Dal`) as actions (`{Function}` as he said), like you might find in some system like:

```
App.User.Create
App.User.Delete
```

But (IMHO), they're abstraction layers, more analogous to:

```
App.Core.User
App.UI.User
```

So if you want to understand our API's interface, you would explore `FrontRow.Api.Handlers.*`. Wouldn't it be nice to get that tree of `Handlers.*` for free in our Haddocks? Similarly, if you want to know how the API accesses data (or if you want to find if a specific data-access function exists), you could explore `FrontRow.Api.Dal.*`.

I think it's actually rare that you'd find major parts of the tree duplicated in between. This idea of `FrontRow.Api.{Namespace}.{Resource}.{Handler,Dal}` isn't really prevalent in our existing modules -- and I don't feel it should be.

The very notion of "Namespace/Resource" is an API / Handler idea. In the _Dal_ layer, it might just be `{Resource}` or `{Type}`. I'm not saying it _must_ be, or that `{Namespace}/{Resource}/Dal` is a bad thing to be avoided, I just think that pushing for (or even passively indicating) that there's a pattern to confirm to of `{Path}.{Handler,Dal}` isn't particularly useful.

To state it another way: the tree under `Dal/` should be smaller than the tree under `Handler/` because `Dal` functions would be re-used, and they should be free to diverge in this way.

```
App.Core.User
  |- <- depends on - App.UI.Admin
  `- <- depends on - App.UI.Guest

FrontRow.Api.Dal.Student
  |- FrontRow.Api.Handlers.Student
  `- FrontRow.Api.Handlers.Teacher.Student
```

---

Anyhoo, those are my thoughts. Either approach would be better, so long as it's standardized. So I'm happy to abide by a vote on this preference.

**Comment by pbrisbin** [comment]
This initiative has stalled. Can I get a quick :+1:/:-1: vote on **only** the following:

*Should we continue discussion and attempt to get a Guide on this?*

@eborden @cdparks @5outh  @jdreaver

**Comment by pbrisbin** [comment]
Silence and one no-vote. It saddens me, but I think I have to Close. Our grab-bag of varying Handler naming lives on.
