### ISSUE TITLE
Add StrictData to default-extensions

### ISSUE THREAD

**Issue by pbrisbin** [freckle/guides#40]
I propose adding `StrictData` to our set of default-extensions.

In my experience, my PRs almost always receive the comment to add it (or `!`s) in any "data-type heavy modules". I'm not sure the distinction is worth it and would rather this be treated as a "sane default".

I don't totally understand the scenarios where it's _not_ desired, but I believe they are rare enough that it's OK to expect a knowledgeable developer know to use the `NoStrictData` pragma in such modules. And a better trade-off for those that don't care to understand things deeply to get the `StrictData` behavior without thinking about it.

WDYT @cdparks @eborden @5outh ?

**Comment by eborden** [comment]
I'd prefer not. It is a very powerful extension that changes a lot of default assumptions about how data works in Haskell. I prefer it being explicit wherever it is used.

**Comment by pbrisbin** [comment]
Are you in favor of codifying the

> add it (or !s) in any "data-type heavy modules"

Comments I typically get?

When I hear

> a very powerful extension that changes a lot of default assumptions about how data works

I don't get the feeling we should just enable it in any module that looks vaguely data-type-heavy.

**Comment by eborden** [comment]
Honestly I think most of our aggressive use of strictifying data is premature optimization :man_shrugging:, but if we are going to do it then I prefer explicit. If explicit is `BangPatterns`, sure. If explicit is `StrictData` in the file pragmas, sure. I just want explicit over implicit.

**Comment by pbrisbin** [comment]
> > Are you in favor of codifying the
> >
> > > add it (or !s) in any "data-type heavy modules"
> >
> > Comments I typically get?
>
>  I just want explicit over implicit

I interpret that as an _abstain_ on that question. You're anti my original proposal but don't have any stance on that one.

I'm fine considering the `default-extensions` proposal dead. I'd like to let conversation on this Issue continue a bit to see if we can suss out a Guide or at least pin down our majority opinion on if/when to add the pragma/bangs.

**Comment by jdreaver** [comment]
If `StrictData` is in `default-extensions`, how can we turn it off for a data type we want to be lazy?

FWIW I use `StrictData` all the time. I'm actually not a fan of lazy-by-default in my data types :grimacing:

**Comment by pbrisbin** [comment]
@jdreaver, there is `NoX` for all `X` AFAIK. Sorry, that was was a bit buried in my original comment:

> ... to expect a knowledgeable developer know to use the `NoStrictData` pragma in such modules

**Comment by jdreaver** [comment]
Yeah I was talking about just for an individual data type. When `StrictData` is not present, we can pepper  `!` wherever we need, but it sucks there isn't a way to un-strictify a field or type.

**Comment by pbrisbin** [comment]
Oh I think that's `~`.

**Comment by jdreaver** [comment]
Haha, I was about to add "I wish we could do something like `~`". Maybe this knowledge was buried in my thick skill :stuck_out_tongue: Good to know!

**Comment by cdparks** [comment]
Yeah, `~` still works in the presence of `StrictData`. The only bit that worries me is generated code, e.g. if you turn on `StrictData` everywhere, I'm not sure all of our `persistent` `TH` behaves the way we expect

**Comment by pbrisbin** [comment]
So, trying to refocus:

1. Adding `StrictData` to `default-extensions`

   No one is really pushing this forward. Some are against. I only proposed it because the comments I received (from @cdparks) on my own PRs made it feel mechanic enough that we might want that. I consider this proposal retracted.

1. Adding a Guide such as _Under {certain circumstances}, prefer {`StrictData` or `BangPatterns`}_

   I'm a soft-no here, but it depends on filling in the *{variables}*. I don't get a strong sense from this thread where others stand on this point. The closest version that matches my own PR review experience would be: _In a module containing data type definitions, add `StrictData`_. But that feels a bit too broad for @eborden's liking. I also tend to agree it's pre-optimization.

   That said, unless someone speaks up, I'll also let this go and not push anything further in this direction.

   However, not having a Guide means there is room for discussion on every PR comment about strictness annotations. The reviewer should have to offer some reasoning, if/when the reveiwee asks for it. Everyone cool with that? Or does anyone want to push to pre-settle it here with some version of a Guide in this area?

**Comment by cdparks** [comment]
> Under {certain circumstances}, prefer {StrictData or BangPatterns}

I think this is -

If you're defining plain records in Haskell, prefer bangs or `-XStrictData`. Avoid bangs or `-XStrictData` if you're defining recursive data types, or nested data types that will be consumed incrementally

**Comment by eborden** [comment]
@cdparks as I understand it, one of the original reasons for strict records was to receive warnings when a field was not initialized. That reason was made redundant when `-Wmissing-fields` made it into `-Wall`. Is that a miss-characterization of history?

**Comment by cdparks** [comment]
That's probably the reason we started using it. The "don't make things lazier than you need" is potentially a bit of a pre-optimization, though if you're serializing a bunch of stuff, it can't hurt

**Comment by pbrisbin** [comment]
:wave: Hello again.

Is anyone advocating for any "Prefer `StrictData`" Guide (in any form)? @cdparks?

Is anyone actively *against* such a Guide? @eborden?

If no answer by EOD today, I'm going to close this Issue and internalize this as the current state-of-affairs:

> [N]ot having a Guide means there is room for discussion on every PR comment about strictness annotations. The reviewer should have to offer some reasoning, if/when the reveiwee asks for it.

**Comment by eborden** [comment]
> Is anyone actively against such a Guide?

I really do think strict or lazy is a case by case issue, so I don't have any desire for a guide. If there were one it would have to be a pretty carefully worded document laying out when and why, but my when and why is usually "have you measured?"

**Comment by jdreaver** [comment]
> I really do think strict or lazy is a case by case issue, so I don't have any desire for a guide. If there were one it would have to be a pretty carefully worded document laying out when and why, but my when and why is usually "have you measured?"

I think there is plenty of room to tell folks to prefer strict fields for "normal" record types (i.e. not recursive, not relying on laziness, etc) without asking them to run a benchmark every time they make a record. Yes, laziness is the default in Haskell, but that doesn't mean it automatically has to be our default for record fields.

FWIW I'm pretty sure every record data type I've written in the past year or so has had strict fields.

**Comment by cdparks** [comment]
I'm advocating for the simplest version of

> If you're defining plain records in Haskell, prefer bangs or -XStrictData

I could see adding qualifiers such as:
1. If you're defining data types _that will be de/serialized in requests/responses_
2. If you're defining data types _that will be stored in the DB_
3. If you're defining data types _that will be read from/written to CSVs_

These are all super common cases where you're gonna force everything anyway, so there's no reason to build up thunks

**Comment by pbrisbin** [comment]
@cdparks Can we pin down _bangs or -XStrictData_ to specifically `LANGUAGE StrictData`? I'm all about consistency through Guides, so I'd prefer they not introduce room for inconsistency themselves. Such a Guide doesn't (IMO) disallow use of `!` or `~` in any more specific scenarios not covered by it.

I also like the qualifiers you mention, and they actually all seem equivalent (HTTP, DB, and CSV are all just different targets for the de/serialization).

So, something like:

> Add `LANGUAGE StrictData` to modules that contain plain records that will undergo de/serialization

I think we have two Advocates (Chris and David) and two neutral (me and Evan), so we should be good for a PR here. :tada: 

(@eborden _I don't have any desire for_ isn't exactly _I'm actively against_, so please speak up if I'm misunderstanding a lack of objection on your part.)

**Comment by eborden** [comment]
I'm fine with @cdparks's qualifiers. I agree on the open question of `StrictData` vs `BangPatterns`.

**Comment by cdparks** [comment]
I'm fine with preferring `-XStrictData` to bangs

**Comment by pbrisbin** [comment]
Opened as #43
