### ISSUE TITLE
Formalize PATCH Semantics for Sub-Resources

### ISSUE THREAD

**Issue by StevenXL** [freckle/guides#71]
# Formalize PATCH Semantics for Sub-Resources

Our Haskell API guide does a great job of laying out the intended behavior for [PATCH endpoints](https://github.com/freckle/guides/blob/main/haskell-api.md#patch-semantics). 

However, the guidelines do not *explicitly* mention what the semantics should be when a *sub-resource* is involved, particularly for an *empty* patch.

For example, the [patchSchoolR](https://github.com/freckle/megarepo/blob/168f167a94503d25a86195759dba6e8ac1b7263e/backend/fancy-api/library/FrontRow/Api/Handlers/Schools.hs#L205) endpoint expects a [SchoolPATCH](https://github.com/freckle/megarepo/blob/168f167a94503d25a86195759dba6e8ac1b7263e/backend/fancy-api/library/FrontRow/Api/Handlers/Schools.hs#L161-L181) body that can contains (nested) patch data for the [RenaissanceSchoolClientPATCH](https://github.com/freckle/megarepo/blob/168f167a94503d25a86195759dba6e8ac1b7263e/backend/fancy-api/library/FrontRow/Api/Handlers/Schools.hs#L143-L150) sub-resource. 

What is the expected behavior when the body is `{}` or `{renaissanceSchoolClient: {}}`, particularly when it comes to the `updated_at` fields. What if the sub-resource is not found? 

Please see [this comment](https://github.com/freckle/megarepo/pull/20600#discussion_r790844143) for further context.

**Comment by pbrisbin** [comment]
I'll throw in my 2c, FWIW...

I think there are two concrete questions here (the title favors one, but I'm not sure that's even the interesting one):

1. Should `PATCH {}` touch `updatedAt`?

   Last we discussed this, I don't think there were any strong trade-offs either way on principle. So lacking a "morally correct" behavior, I like to ease likely implementations.

   For example,

   ```hs
   now <- getCurrentTime
   body <- requireJsonBody
   runDB $ update fooId $ toUpdates body <> [FooUpdatedAt =. now]
   ```

   In this case, it is simplest to allow an empty patch (and so `updates == []`) to still touch `updatedAt`. Therefore, I do not think we should mandate that an empty patch _doesn't_ do that. Personally, I also see no need to mandate that it _does_. So, IMO, we shouldn't have a guide on `updatedAt` and empty `PATCH`, but we can certainly add an explicit note that it's acceptable to do either.

1. What should `PATCH: { field: {} }` mean?

   This is the assignment of `{}` to `field`. What _outcomes_ this results in will always be endpoint-by-endpoint, I think. I just don't see any ambiguities or competing "reasonable" options that need to be made consistent through some Guide. Sometimes such an action may need to 404 on sub-resource not found, or sometimes the sub-resource might be created if necessary. It all depends on how the App interprets some action on the sub-resource as a "change" to the parent.

**Comment by StevenXL** [comment]
> I'll throw in my 2c, FWIW...
> 
> I think there are two concrete questions here (the title favors one, but I'm not sure that's even the interesting one):
> 
> 1. Should `PATCH {}` touch `updatedAt`?
>    Last we discussed this, I don't think there were any strong trade-offs either way on principle. So lacking a "morally correct" behavior, I like to ease likely implementations.
>    For example,
>    ```haskell
>    now <- getCurrentTime
>    body <- requireJsonBody
>    runDB $ update fooId $ toUpdates body <> [FooUpdatedAt =. now]
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    In this case, it is simplest to allow an empty patch (and so `updates == []`) to still touch `updatedAt`. Therefore, I do not think we should mandate that an empty patch _doesn't_ do that. Personally, I also see no need to mandate that it _does_. So, IMO, we shouldn't have a guide on `updatedAt` and empty `PATCH`, but we can certainly add an explicit note that it's acceptable to do either.
> 2. What should `PATCH: { field: {} }` mean?
>    This is the assignment of `{}` to `field`. What _outcomes_ this results in will always be endpoint-by-endpoint, I think. I just don't see any ambiguities or competing "reasonable" options that need to be made consistent through some Guide. Sometimes such an action may need to 404 on sub-resource not found, or sometimes the sub-resource might be created if necessary. It all depends on how the App interprets some action on the sub-resource as a "change" to the parent.

I'm satisfied with the current guidelines on what should happen to the top-level resource in regards to the `updated_at`. The clarity of the guidelines removes an extra decision that would otherwise needs to be made. 

In terms of the sub-resource, I am in favor of interpreting the sub-resource data as if it were top level. If we do that, then`{}` doesn't touch the sub-resource at all, `{field: {}}` will 404 if the resource can't be found and will update the _updated_at` if the sub-resource can be found. 

This interpretation breaks down in case of creating a sub-resource when it doesn't exist and the patch is coherent (in terms of creating a sub-resource). The guidelines at the moment suggest a PATCH _does not_ create a new resource, but we _are_ creating a new sub-resource in `patchSchoolR`. 🤔

**Comment by pbrisbin** [comment]
> I am in favor of *interpreting the sub-resource data as if it were top level*.

This just seems like a weird leap to make about how someone's API needs to function. Can you say more as to why that's beneficial?

>  If we do that, then `{}` doesn't touch the sub-resource at all, `{field: {}}` will 404 if the resource can't be found and will update the `_updated_at` if the sub-resource can be found.

So are you are advocating a very caveat-ed Guide such as:

> A `PATCH` of some sub-resource `field:` which is itself an entity with timestamps, must set `update_at` even if assigned `{}`

?

I ask because, even if some resource has a `{ field: Object }` type, that doesn't say anything about that sub-resource being DB-backed or having timestamp fields. It seems weird for our Guides to assume it and/or cater to it as a use-case -- even our on API likely does it less often than not.

> This interpretation breaks down in case of creating a sub-resource when it doesn't exist and the patch is coherent (in terms of creating a sub-resource). The guidelines at the moment suggest a PATCH does not create a new resource, but we are creating a new sub-resource

This is what I meant by,

> It all depends on how the App interprets some action on the sub-resource as a "change" to the parent.

A `PATCH` is a list of changes to the resource. Creating a *sub-* resource is a perfectly valid "change" to that resource, IMO.

> a PATCH does not create a new resource

Here, "resource" means "the resource pointed at by the URL", e.g. `PATCH /schools/x` should not create the School with `id=x`. That's the only requirement.

It's not saying the endpoint can't create _any_ resources ever. All sorts of things can occur behind the scenes of an endpoint. Just because something over here is created or deleted doesn't mean you've violating REST. Similarly, if one endpoint takes `{ field: {} }` and does an update or create and another does an update or 404, that's all fine.

Also, if you want to get really philosophical, if `PATCH /schools/:id` accepts a `{ something: { } }`, but there is no `/somethings` tree in our API, is `something` even a "resource" anyway?
